### ISSUE TITLE
GUI Request

### ISSUE THREAD

**Issue by Redemp** [zigurana/EmulationStation#13]
I got a request for the UI Kids mode.
Is it possible to remove the option Shutdown in the context menu and only have Reboot & Restart?

**Comment by zigurana** [comment]
Sure, everything is possible.
I am contemplating a new setting that will allow you to choose these menu items using a bit flag approach, where each bit corresponds to a menu item to include or not.
It's not the first thing on the todo list though, so don't hold your breath. (alternatively, you are more than welcome to have a stab at it, and submit a PR!).

**Comment by zigurana** [comment]
Not going to pick this up anytime soon
