### ISSUE TITLE
Further favorites integration

### ISSUE THREAD

**Issue by henrikp** [zigurana/EmulationStation#14]
Started using this "kids" version due to the favorites and kiosk addition and currently it's bit hard to see what you have marked as a favorite outside metadata edit. So I propose:
- either add md_lbl_favorite ("Favorite") md_favorite ("Yes" or "No") for themes
  or
- if possible without rewriting much, make the game name bold in the game list, probably only when the whole list is displayed only.

**Comment by opensourcefan** [comment]
If you install the Carbon V4 theme it will show a big heart on the top for favorite games. 

https://github.com/retropie/retropie-setup/wiki/Child-friendly-EmulationStation#themes

**Comment by henrikp** [comment]
Currently using v4 theme, but after writing this I found out that both the 'favorite' and the 'kids only' shortcuts don't do anything, even metadata stays the same. I'm sure I'm using the right version, I have the ability to switch between Kiosk and Full mode. Using X and Y in games works fine (SNES clone USB pad) Any suggestions?

**Comment by opensourcefan** [comment]
Yep, I just wrote that bug up today. I can only get the shortcut buttons to work immediately after configuring a controller, once I play and exit a game or reboot that ability is lost.

**Comment by zigurana** [comment]
Ok, I'll close this one down, #15 will continue this thread.
