### ISSUE TITLE
Scrape: "No Gamed Found - Skip" not skipping. 

### ISSUE THREAD

**Issue by opensourcefan** [zigurana/EmulationStation#19]
From within the single game edit games metadata menu, it will not skip when activate the No Games Found - Skip, you have to choose CANCEL from the bottom buttons or use your mapped back button. Not a big concern really, just unexpected. 

This does work correctly outside the single game edit metadata menu.

**Comment by zigurana** [comment]
Do you think this is specific for the KidmodeUI fork?
If so, Ill try to have a look at it, (but you've seen how long that might take...) Otherwise, your issue might be better of at the @Herdinger fork.

**Comment by opensourcefan** [comment]
I must admit I can't quite remember if the stock ES had the ability to scrape just a single rom from within a edit metadata menu when in the emulator rom list. For some reason I was thinking that was added with the Kid version. This only happens from within the menu when inside the emulator and choosing a specific rom to edit the metadata on. I hope I'm explaining this so you can understand?
