### ISSUE TITLE
Sub Directories Not Showing in Emulator Rom Lists. 

### ISSUE THREAD

**Issue by opensourcefan** [zigurana/EmulationStation#20]
As the title suggests sub directories to do not show when browsing within the emulator ROM list. The _folder_ entry exists in the gamelist.xml but the sub directory does not show. Prior to installing this version of ES I had two sub directories in my Dreamcast ROM folder. After this installation they no longer showed even thought the directories were still there with their ROM files and the _folder_ entries were still present in the gamelist.xml after this install.

**Comment by BuXY** [comment]
Two additions:
- If there are no game files but only subdirectories in the platform's root folder, ES **crashes** badly!
- The game count (including games in subdirectories) is displayed correctly on the main screen (ie. platform selection).

**Comment by benthecartoon** [comment]
I have the same issue: all sub-folders disappeared after installing the Child-Friendly mod.

**Comment by zigurana** [comment]
Ok, if you could reinstall, this issue should be fixed now.
I've tried to test this, but I am sure you guys can come up with use-cases that I have not thought of. So please give it a test on something other than your 'production system'. Any feedback is appreciated.
