### ISSUE TITLE
System Shutdown / Command Line not working 

### ISSUE THREAD

**Issue by benthecartoon** [zigurana/EmulationStation#21]
The new build to fix the subdirectory display issue introduced a new issue. When selecting System Shutdown or hitting F4 to go to the command line, the screen goes completely black and only a blinking _ underscore is displayed. The system does not shutdown nor does it exit to the command prompt, respectively.

**Comment by zigurana** [comment]
Strange, it does for me. Do you have many games installed, and do you have "save metadata on exit" set to on or off?
~~In any case, pressing F4 should work, that does not rewrite the XMLs at all.~~ (ed: it seems it does).
How did you install, via the experimental menu of RetroPie-setup?

**Comment by benthecartoon** [comment]
Yes. I do have quite a bit of games, and save metadata is set to On, but this was not a problem before installing the mod, which yes, I installed through the experimental menu.

**Comment by zigurana** [comment]
I am unable to replicate this issue.

**Comment by benthecartoon** [comment]
I resolved it by starting a fresh install and activating Child-Friendly before adding any games. The first shutdown took a while but then every time after has been fine. 
I think the issue possibly came from trying to install the Child-Friendly package on top of everything instead of doing it first on a fresh install.

**Comment by benthecartoon** [comment]
Sorry for not closing the issue earlier, I had forgotten it was still open.
