### ISSUE TITLE
Child-Friendly Icon

### ISSUE THREAD

**Issue by mattrixk** [zigurana/EmulationStation#23]
I'm creating a new theme for RetroPie based on the Pixel theme and I want to make it play nicely with the Child Friendly ES. I have it all working fine (shortcut X and Y keys work), but I'm having a problem with the icons. They show as a grey colour on every game, whether they are set as favourite/kid/hidden or not.

I am using your SVG icons, with the same code as you, just with different size and position. Is there a setting I am missing somewhere? Do I need to set the transparency in the <color> element? I looked in your Carbon_v4 theme and couldn't see anything like that.

Let me know any other info you might need.

**Comment by zigurana** [comment]
Hey, nice of you to try and incorporate these into your theme.
The icons should either show or not show, based on the metadata value. The default color is grey (so they would blend nicely with most themes, or so I thought).
Do you mean they are always showing, even while you toggle them using the shortcut keys?

**Comment by mattrixk** [comment]
Correct. They always show even when you toggle with the shortcut keys. When you toggle them you can see they go (very) slightly brighter when on, then back to grey when off.

This is the code I'm using

```
<image name="md_favorite, md_kidgame, md_hidden" extra="true">
    <origin>0.5 0.5</origin>
    <maxSize>0.03 0.055</maxSize>
</image>

<image name="md_favorite" extra="true">
    <pos>0.470 0.620</pos>
    <path>./art/icon_favourite.svg</path>
</image>
<image name="md_kidgame" extra="true">
    <pos>0.525 0.620</pos>
    <path>./art/icon_kid.svg</path>
</image>
<image name="md_hidden" extra="true">
    <pos>0.580 0.620</pos>
    <path>./art/icon_hidden.svg</path>
</image>
```

Also, I'm using `<formatVersion>4</formatVersion>` because they didn't work at all with `<formatVersion>3</formatVersion>`, but I don't actually understand what that means.

---

I just realised I have [extra="true"] at the end, but you don't have that in yours... could that be it? I won't have the chance to test it until the weekend unfortunately.

**Comment by mrnohr** [comment]
I have been working on [a theme](https://github.com/mrnohr/es-theme-cool-blue) using these icons and they are working as expected. Just another data point. 

Can you share the theme code? 

If it helps, I also am using `<formatVersion>4</formatVersion>` and do NOT have `extra="true"`.

**Comment by mattrixk** [comment]
@mrnohr: Your theme looks really nice, soothing even. Does each system have a different image on the System View, or is it the same image behind each system? How many systems can it handle before it whitescreens?

I haven't had a chance to test the "extra=true" idea, but I'm pretty sure that would be it. Once I've got that fixed up, I can then add it to my other themes as well.

**Comment by mattrixk** [comment]
@zigurana, @mrnohr: I have tested it now, and it was the "extra=true" that was messing up the icons. I have updated my [MetaPixel theme](https://github.com/mattrixk/es-theme-metapixel) with the correct code. Now I have to add them to my [Spare](https://github.com/mattrixk/es-theme-spare) and [Io](https://github.com/mattrixk/es-theme-io) themes too.

**Comment by zigurana** [comment]
Glad you got this sorted!
