### ISSUE TITLE
Enchancement: Add 'Favorites' to Systems and/or top of GameList?

### ISSUE THREAD

**Issue by gehrleib** [zigurana/EmulationStation#24]
Would it be possible to add 'Favorites' to the system wheel similar to Recalbox?

Another: Display favorites first by default, followed by remaining games. Favorites are meant to be accessed quickly. I can almost navigate to the 'favorite' faster than to filter then navigate.

**Comment by zigurana** [comment]
No, not without a significant overhaul of the system wheel (and a break in the UI design behind it).

I would prefer a 'last played' list for ease of acces to games that are currently the most favorite ones.
