### ISSUE TITLE
Feature Request: key shortcut for Jump to next/previous letter

### ISSUE THREAD

**Issue by almaesdi** [zigurana/EmulationStation#26]
Hello

ES it a very great project, i use it on my raspberry. 
But compared with other front ends (like attract mode or maximus arcade) dont have key shorcuts to jump to next letter in the rom list.
I know exist in the menu a "jump to letter" option, but i have disabled my menus, i dont like any person can edit my configurations. So is most useful a button mapped with this option and jump automatically to the next/previous letter from where i am.

Its possible make this function and map them in the L/R Triggers?

I can try to do this, but i need help, like which files i need to edit. I was thinking copy and adapt the GuiFastSelect code and map them to key event.

Thanks

**Comment by zigurana** [comment]
Currently, the shoulders and triggers are mapped to the same keys (pg up and pg down) This is done in the normal ES, and the RetroPie setup scripts ([see here](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh#L51)).
I also feel that skipping ten items on the list is a very comparable functionality to skipping to the next letter. But then again, I am not a typical game-hoarder, so your milage may vary...

If you are using the Kids-mode UI branch, why are you worrying about others touching your configurations?
