### ISSUE TITLE
"Options" Menu takes a long time to close

### ISSUE THREAD

**Issue by pjft** [zigurana/EmulationStation#29]
I'm pretty sure it wasn't like this on the main branch.
Am on RetroPie 4.0.2, installed the child-friendly experimental package. I'm on the Simple theme, though on Carbon it is the same. 
I wonder what's happening to cause this delay. Are you doing any big processing work when we close the "Options" menu?
Anything I can provide from my end? 
Thanks for putting this together!

**Comment by zigurana** [comment]
Hey, yeah I'm not sure why the select menu takes so long. I am seeing the
same thing (but I'm at a party right now, so I cant do any debugging
without disturbing someones pacman tournament :-)  ).
If you are interested in debugging this, you can start ES with the "-debug"
switch, that way , you can probably see what ES is doing.

Op vr 16 sep. 2016 23:48 schreef pjft notifications@github.com:

**Comment by pjft** [comment]
Not at all, please. I'll try debugging it in the coming days and report back, certainly. 
Thanks!

**Comment by pjft** [comment]
Hm. I tried it with -debug but nothing interesting comes up, unfortunately.
I get a couple of warnings when opening the menu

lvl1:   OptionListComponent too narrow!
lvl1:   OptionListComponent too narrow!
lvl2:    req sound [detailed.menuOpen]
lvl2:      (missing)

but I suspect it might be theme related. Nothing that'd suggest what's happening with opening and closing the options menu, sorry :(

Let me know if there's anything else I can do to help.

**Comment by zigurana** [comment]
I've found the issue, will post once I've finished testing is thoroughly.

**Comment by pjft** [comment]
Oh, wow! Great to hear. Let me know if I can help.

**Comment by zigurana** [comment]
I think this is fixed by now.

**Comment by pjft** [comment]
Thanks!
