### ISSUE TITLE
ALSA underrun / no sound on emulationstation?

### ISSUE THREAD

**Issue by pjft** [zigurana/EmulationStation#31]
I am under the impression that there used to be a sound when moving in the theme - a gentle "click". Still, while that may be related to the theme, I do get an ALSA underrun log on my command line when exiting emulationstation, so I suspect there's some problem there. Unsure what more information I can share.
That being said, it doesn't seem to manifest itself in any practical way, so it's low priority. I'll update if I narrow this down a bit more.

**Comment by pjft** [comment]
So, a few more notes. I do get sound in some themes, so it would be theme related. 
That being said, the ALSA underrun log will show up regardless of whether I'm using a theme with sound or not.

**Comment by zigurana** [comment]
I've briefly looked at this, and I think the ALSA underrun is a very comon, as well as generic, error message. Probably related to the shabby way sound effects are implemented in ES or due to the theme. Not something I have touched (yet). I'm closing this for now.

**Comment by pjft** [comment]
Sounds good, thanks!
