### ISSUE TITLE
Feature Request: Option to have Button press for Random

### ISSUE THREAD

**Issue by pjft** [zigurana/EmulationStation#32]
Hi.
I know this is a long shot, but I love the "Surprise Me" option - except for the fact that it requires entering a menu and selecting an option, as it takes too long (though it may be related to #29). The reason for it is that some times we just want to be shown several options until I find one that we feel like playing at the time.
Any chance to have the option to tie it to a button?
Just a thought. 
Thanks!

**Comment by zigurana** [comment]
Hey!
It's an interesting idea, and not difficult to do. But really, we are running out of free buttons! (especially when ppl are using older controllers or arcade setups). 

We currently have: A/B/start/select/Lshoulder/Rshoulder/Ltrigger/Rtrigger taken up by vanilla ES.
For the Kidmode UI stuff, I've tried to add X and Y. That leaves very few buttons for most people.

So alternatively, you could think about some user-defined button mapping system, where the function of the two/four free buttons can be set by the user. This would then need to be propagated through the GUI menus and help-texts.
I'm not quite sure I feel up to that, after my recent fiasco reg the filtering redesign...

As always, a PR is more than welcome!

**Comment by pjft** [comment]
Makes sense, I fully get that :)

I wouldn't want to go the route of fully-blown button map, as that's hell
to implement - and then even to merge with vanilla ES, even though the
development there seems to have been fairly stalled for the last year or so.

I don't have a real suggestion at the moment, and as I stated, maybe after
#29 is solved, this actually isn't as much of a problem, as right now what
makes it problematic is that it takes a lot of time to select a new random
game, though I'm not sure how much of it is related to the Options Menu
closing, vs actually selecting the game (I'd suspect selecting the game
shouldn't be that demanding).

So we can wait on this for a moment.

One use case, though, where this is a bit more relevant, is in Kiosk and
Kid mode, as in those modes I don't expect people to be editing the
Kid-Friendly metadata (the favorite one I still think makes sense). As
such, in those modes, the Kid-Friendly button could become the random one -
maybe as an option, if not by default. I can understand if it'd be weird to
have the same button do two different things in different ES settings.

Just food for thought. :)

Thanks! Hope you had a good weekend.

**Comment by zigurana** [comment]
That's actually a pretty good suggestion. It would set the Full mode to be more of an SU mode, i.e. not something to spend a lot of time in. The kiosk-mode would then be the de-facto standard, 

Thanks for the discussion! (And keep the issues coming please!)

**Comment by pjft** [comment]
By all means, thanks for the openness! I love this project, as I'm building this so that one day I can play my childhood games with my kids. Let me know if I can help.

**Comment by pjft** [comment]
Just for clarity - this is mostly a problem because of the slow closing of the Options Menu in #29 .

When it opens and closes quickly, it really works fine as is.

**Comment by pjft** [comment]
Hi!

Wanted to reach out as I have a quick question, but had no other means of contacting you :) 

Have you ever tried to commit to master just the random game selection? It seems there's quite a few people wanting that.

If you have, I won't redo the work, but if not, I might take a shot at that from the implementation in the fork I've been working from. Would you oppose that in any significant way?

Thanks!

EDIT: and I'll probably tie it both to the menu, but also to "select" on the system view menu as it's free.

**Comment by pjft** [comment]
Actually, scrap that - you already did all the work, in a much more elegant way than I had. :)

https://github.com/fieldofcows/EmulationStation/pull/16/files

Has this been submitted to the master branch? It could easily be split from the screensaver functionality and just make it work seamlessly.

**Comment by zigurana** [comment]
This is in the master-branch, closing this issue
