### ISSUE TITLE
lvl10: Trying to set using unset ShowHidden

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [zigurana/EmulationStation#36]
As the title said.
The message is shown several times during loading an emulator or exiting (whenever the console is shown during transition between emulator and ES).

I tried to recompile it several times and the problem still there.

Also sometimes ES is freezing for a minutes or so after exiting emu, like its processing something big, then it works again.

**Comment by zigurana** [comment]
Hey, this is on the UI_modes_Kids_Kiosk_Full branch, I presume?

**Comment by Crescendo-BLYAT** [comment]
yes... :)

**Comment by zigurana** [comment]
I'll have a look, cannot make any promises on timing though.

**Comment by Crescendo-BLYAT** [comment]
thanks a lot...
And could you please also implement fast shutdown?
https://github.com/RetroPie/EmulationStation/pull/65

Coz its taking ages to load + exit with large 5k+ romset.

Thank you again so much.

**Comment by pjft** [comment]
Same here, this is happening after updating RetroPie to the latest version - maybe a conflict related to some change upstream. Updated everything, then installed the kids version.

In my case, it just seemed to be showing the "emulation station" start screen, constantly flickering on startup, so I thought it had actually just crashed permanently. Had to F4 to go to command line, run RetroPie Setup script.

Any information on how we may help?

Best.

**Comment by Crescendo-BLYAT** [comment]
no crash here, just very slow load + exit....

**Comment by EddyK69** [comment]
Had the same issue.
Got rid of the error when i edited es_settings.cfg and added 
`<bool name="ShowHidden" value="true" />` :D

**Comment by zigurana** [comment]
Hey, thanks @EddyK69, that was indeed the bug, should be fixed now, but in any case, I'm picking up the UImodes branch dev again to deliver to RetroPie/master.
