### ISSUE TITLE
Child Friendly Package Crashing on Favorites Filter

### ISSUE THREAD

**Issue by ebTalk** [zigurana/EmulationStation#37]
What if this happens when I have multiple games set as favorite.
I made sure I had at least three games set to favorites per emulator. I changed my view to Favorites On. Everything worked.

I then changed my view to show all games. It sent me back to the command line and crashed.

**Comment by ohohone** [comment]
I have the exact same issue.

**Comment by armstrong1118** [comment]
I also am having the same issue.

**Comment by jclark-dot-org** [comment]
Same issue, except that when I get dumped to console, it is non-responsive.  I have to ssh into the pi and force a reboot from there.  Happy to provide any logs, etc.  I am also unable to set favorites from inside emulation station; it appears to hang.  I've taken to editing gamelist.xml and restarting emulationstation.  As noted by @ebTalk, toggle _into_ Favorites mode is fine; toggling out causes the crash.

Newly installed retropie, from retropie-4.1-rpi2_rpi3.img; installed this branch via `retropie-setup` per [these instructions][1].  Emulationstation's main menu reports V2.0.1A_GUI_MODES_V7.  

[1]: https://github.com/RetroPie/RetroPie-Setup/wiki/Child-friendly-EmulationStation

**Comment by zigurana** [comment]
This should be more stable now, if not completely solved.
If you do not want to try another of these all-or-nothing builds, I am working on delivering this to Retropie/master properly, starting with the favorites functionality. So wait another couple of weeks, and see if it has landed there.

**Comment by ohohone** [comment]
You're awesome Ziguaran! I can't wait to give it another shot tonight. Thank you so much!
