### ISSUE TITLE
Star in front of favorites

### ISSUE THREAD

**Issue by daeks** [zigurana/EmulationStation#38]
Hi Zigurana,

is it possible to add a star in front of favorite games? Similar to https://github.com/recalbox/recalbox-emulationstation/commit/a2c3b7d3a2b918845fbfa9494097920def5e9453

**Comment by zigurana** [comment]
I'll put it on the list of enhancements.

Op za 14 jan. 2017 10:32 schreef daeks <notifications@github.com>:

**Comment by zigurana** [comment]
Please have a look at [this forum thread](https://retropie.org.uk/forum/topic/10213/favorites-for-emulationstation/111), for some more background on this issue
