### ISSUE TITLE
Rom subfolders with actual rom files in them cause ES Kid friendly to crash on startup

### ISSUE THREAD

**Issue by qphoria** [zigurana/EmulationStation#44]
If you have your roms in subfolders like

nes
  |__A
  |__B
    |__ Battletoads.nes

ES crashes on startup. If all roms are directly under the emulator folders like 
nes
  |__ Battletoads.nes

it works fine.

**Comment by qphoria** [comment]
This appears to have been fixed at some point between the 2.0.3 and in the 2.1.6 version. Thank you!

**Comment by zigurana** [comment]
great! (issues that go away automagically are the best, if slightly unsettling...)
