### ISSUE TITLE
Update for video support?

### ISSUE THREAD

**Issue by nikkoman** [zigurana/EmulationStation#47]
I would like to know if it's possible to update to the latest version of EmulationStation for RetroPie that supports videos.

I updated (reverted back to) EmulationStation-kids while my themes were updated for videos and that resulted in bricking my setup (I'll probably fix it).

**Comment by nikkoman** [comment]
Any news on this? :)

**Comment by zigurana** [comment]
You can try it now!

Op zo 30 apr. 2017 03:10 schreef Nicholas <notifications@github.com>:

**Comment by nikkoman** [comment]
Fantastic! Thanks!
