### ISSUE TITLE
Goes to top of list after quitting a game 

### ISSUE THREAD

**Issue by roadie** [zigurana/EmulationStation#49]
Every time I quit a game, it goes back to the top of the list. I have hundreds of game so it's frustrating having to scroll down to the game I was playing. Is there any way to fix it?

**Comment by nikkoman** [comment]
Same problem here. It's an actual bug of the latest version. It also happened briefly on the original 2.1.6 and was quickly fixed (along with a video flashing bug that's also present), therefore I think the current version was forked from that source. Nevertheless, I'm very happy about video support and once this is fixed, we'll have a perfect kiosk GUI :)

**Comment by zigurana** [comment]
Acknowledged, I'll have a look when I get the chance.

Op di 2 mei 2017 15:57 schreef Nicholas <notifications@github.com>:

**Comment by qphoria** [comment]
Heh I was just asking about this in the forums https://retropie.org.uk/forum/topic/10050/rp4-2-exit-game-returns-to-top-of-the-list/10

**Comment by zigurana** [comment]
@roadie , @nikkoman , @qphoria :
I've pushed an update for this (actually, amended the previous commit, so it does not show up as yet another separate fix commit). It was the result of me not taking care of business properly, so I actually forgot to finish this. It's kind of tricky territory, with a small chance of empty list => failing assertions => crashing ES, so please make a proper backup before you try this out.
I would appreciate it if anyone could give this a test! Especially toggling favorites while in 'show only favorites' mode, and getting to empty lists.

**Comment by nikkoman** [comment]
Updated yesterday night, it seems to be working fine :)

I apparently have no favourites lists, I tried testing it out and seems to have no problems but it was just a quick check.

Has also the random GUI crashing issue been fixed? I didn't experience it at all last night even after browsing through thousands of video previews but it happens very randomly anyway.

**Comment by qphoria** [comment]
I confirm it is working for me too. Thank you so much! This is huge for me.
How can we donate to you @zigurana ?
And would you take bounties for a few other features?

**Comment by zigurana** [comment]
Hey, good to hear it's helped for this issue. 
If you want to donate, please donate to @Joolswills via the RetroPie project, he does a lot more work than I do, and may have good goals for the money they make (server upgrades and whatnot). See [here](https://retropie.org.uk/donate/)

If there are other features that you are interested in, please bring them up in the forum, so we can see if other might be interested as well.
